= Vue.js notes

== Installation

There are four primary ways of adding Vue.js to a project:

* Import it as a CDN package on the page
* Download the JavaScript files and host them yourself
* Install it using npm
* Use the official CLI to scaffold a project, which provides batteries-included build setups for a modern frontend workflow 

=== Installing with npm

----
$ npm install vue@next
----

Vue provides an official CLI (opens new window) for quickly scaffolding ambitious Single Page Applications. It provides batteries-included build setups for a modern frontend workflow. It takes only a few minutes to get up and running with hot-reload, lint-on-save, and production-ready builds.

=== Installing and using Vue Cli

----
$ npm install -g @vue/cli
$ vue create <my_project_name>
$ cd <my_project_name>
# code . 
$ npm run serve
----



== Options

- data(): {}
  The function that returns a data object for the component instance. 
  In data, we don't recommend to observe objects with their own stateful 
  behavior like browser API objects and prototype properties. 
  A good idea would be to have here just a plain object that represents component data.

- props: { } 
  A list/hash of attributes that are exposed to accept data from the parent component. 
  It has an Array-based simple syntax and an alternative Object-based syntax that allows 
  advanced configurations such as type checking, custom validation and default values.

- computed:{ } 
  Computed properties to be mixed into the component instance. 

- watch: { }
  Watch a reactive property or a computed function on the component instance for changes. 
  The callback gets called with the new value and the old value for the given propert
  An object where keys are reactive properties to watch — examples include data or 
  computed properties — and values are the corresponding callbacks. The value can 
  also be a string of a method name, or an Object that contains additional options
  NOTE: you should not use an arrow function to define a watcher 
  (e.g. searchQuery: newValue => this.updateAutocomplete(newValue)). 
  The reason is arrow functions bind the parent context, so this will not be the component 
  instance as you expect and this.updateAutocomplete will be undefined.

- methods:{}   
  Methods to be mixed into the component instance. 
  You can access these methods directly on the VM instance, or use them in directive expressions. 
  All methods will have their this context automatically bound to the component instance.
  You should not use an arrow function to define a method (e.g. plus: () => this.a++). 
  The reason is arrow functions bind the parent context, 
  so this will not be the component instance as you expect and this.a will be undefined.

- emits: { }  
  A list/hash of custom events that can be emitted from the component. It has an array-based 
  simple syntax and an alternative Object-based syntax that allows to configure an event validation.

- Lifecycle hooks: 
  All lifecycle hooks automatically have their this context bound to the instance, so that you can access data, 
  computed properties, and methods. This means you should not use an arrow function to define a lifecycle method 
  (e.g. created: () => this.fetchTodos()). The reason is arrow functions bind the parent context, so this will 
  not be the component instance as you expect and this.fetchTodos will be undefined.

- created() { }
  Called synchronously after the instance is created. At this stage, the instance has finished processing the options 
  which means the following have been set up: data observation, computed properties, methods, watch/event callbacks. 
  However, the mounting phase has not been started, and the $el property will not be available yet.

- mounted() { }
  Called after the instance has been mounted, where element, passed to app.mount is replaced by the newly created vm.$el. 
  If the root instance is mounted to an in-document element, vm.$el will also be in-document when mounted is called.
  Note that mounted does not guarantee that all child components have also been mounted. 
  If you want to wait until the entire view has been rendered, you can use vm.$nextTick inside of mounted